// <auto-generated />
using System;
using Adaptit.Training.JobVacancy.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adaptit.Training.JobVacancy.Persistence.Migrations
{
    [DbContext(typeof(JobVacancyDbContext))]
    [Migration("20250127141110_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adaptit.Training.JobVacancy.Persistence.Model.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomePageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NextId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NextId");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("Adaptit.Training.JobVacancy.Persistence.Model.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeedEntryUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeedEntryUuid");

                    b.HasIndex("FeedId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Adaptit.Training.JobVacancy.Persistence.Model.feedEntry", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Municipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SistEndret")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.ToTable("feedEntries");
                });

            modelBuilder.Entity("Adaptit.Training.JobVacancy.Persistence.Model.Feed", b =>
                {
                    b.HasOne("Adaptit.Training.JobVacancy.Persistence.Model.Feed", "Next")
                        .WithMany()
                        .HasForeignKey("NextId");

                    b.Navigation("Next");
                });

            modelBuilder.Entity("Adaptit.Training.JobVacancy.Persistence.Model.Item", b =>
                {
                    b.HasOne("Adaptit.Training.JobVacancy.Persistence.Model.feedEntry", "FeedEntry")
                        .WithMany()
                        .HasForeignKey("FeedEntryUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adaptit.Training.JobVacancy.Persistence.Model.Feed", "Feed")
                        .WithMany("Items")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feed");

                    b.Navigation("FeedEntry");
                });

            modelBuilder.Entity("Adaptit.Training.JobVacancy.Persistence.Model.Feed", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
